---
- hosts: docker1.example.com
  remote_user: root
  tasks:
    - name: Create ansible user
      user:
        name: ansible
    - name: Install the ssh-key
      authorized_key:
        key: "{{ lookup('file', '/home/ansible/.ssh/docker-node1.pub') }}"
        user: ansible
    - name: Configure sudo privileges 
      copy:
        src: ansible
        dest: /etc/sudoers.d/ansible

