---
- hosts: proxy
  become: true
  vars:
    - haproxy_backend_servers:
        - name: app1
          address: 192.168.0.22:80
  roles:
    - geerlingguy.haproxy

  tasks:
    - name: Start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: Configure firewalld
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes
    

