---
- hosts: webservers
  become: true
  vars_files:
    - secret.yml
    - user_list.yml
  tasks:
    - user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
      when:
        - item.uid is match("^1")
      loop: "{{ user_list }}"
    - authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
        state: present
      loop: "{{ user_list }}"
      when:
        - item.uid is match("^1")
    - user:
        name: "{{ item.username }}"
        groups: wheel
        append: yes
      loop: "{{ user_list }}"
      when:
        - item.uid is match("^1")
   

- hosts: database
  become: true
  vars_files:
    - secret.yml
    - user_list.yml
  tasks:
    - user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
      loop: "{{ user_list }}"
      when:
        - item.uid is match("^2")
    - authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
        state: present
      loop: "{{ user_list }}"
      when:
        - item.uid is match("^2")
    - user:
        name: "{{ item.username }}"
        groups: wheel
        append: yes
      loop: "{{ user_list }}"
      when:
        - item.uid is match("^2")
